version: https://archlens.dev/schemas/v4/blueprint.schema.json
level: component
metadata:
  entityRef: backstage/packages/repo-tools/commands/repo/schema/openapi
  name: Openapi Components
  source:
    remoteUrl: https://github.com/backstage/backstage
    defaultBranch: master
    scannedAtCommit: a052aea0e24911fcac803085ed79f3fe23e0a46e
    scanRoot: .
nodes:
  - entityRef: backstage/packages/repo-tools/commands/repo/schema/openapi/lint
    type: background-worker
    name: Lint
    isTest: false
    properties:
      filepath: packages/repo-tools/src/commands/repo/schema/openapi/lint.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
  - entityRef: backstage/packages/repo-tools/commands/repo/schema/openapi/fuzz
    type: background-worker
    name: Fuzz
    isTest: false
    properties:
      filepath: packages/repo-tools/src/commands/repo/schema/openapi/fuzz.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
  - entityRef: backstage/packages/repo-tools/commands/repo/schema/openapi/verify
    type: background-worker
    name: Verify
    isTest: false
    properties:
      filepath: packages/repo-tools/src/commands/repo/schema/openapi/verify.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
  - entityRef: backstage/packages/repo-tools/commands/repo/schema/openapi/diff
    type: background-worker
    name: Diff
    isTest: false
    properties:
      filepath: packages/repo-tools/src/commands/repo/schema/openapi/diff.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
  - entityRef: backstage/packages/repo-tools/openapi/constants
    type: background-worker
    name: Constants (External)
    external: true
    properties:
      filepath: packages/repo-tools/src/lib/openapi/constants.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
    position:
      x: 790
      y: 404
  - entityRef: backstage/packages/repo-tools/openapi/helpers
    type: background-worker
    name: Helpers (External)
    external: true
    properties:
      filepath: packages/repo-tools/src/lib/openapi/helpers.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
    position:
      x: 1250
      y: 404
  - entityRef: backstage/packages/cli-node/index
    type: background-worker
    name: Index (External)
    external: true
    properties:
      filepath: packages/cli-node/src/index.ts
      containerId: cli-node
      technology: TypeScript Domain Service
      classification: default
    position:
      x: -130
      y: 404
  - entityRef: backstage/packages/cli-common/index
    type: background-worker
    name: Index (External)
    external: true
    properties:
      filepath: packages/cli-common/src/index.ts
      containerId: cli-common
      technology: TypeScript Domain Service
      classification: default
    position:
      x: -590
      y: 404
  - entityRef: backstage/packages/backend-plugin-api/index
    type: background-worker
    name: Index (External)
    external: true
    properties:
      filepath: packages/backend-plugin-api/src/index.ts
      containerId: backend-plugin-api
      technology: TypeScript Domain Service
      classification: default
    position:
      x: -1050
      y: 404
  - entityRef: backstage/packages/repo-tools/commands/util
    type: background-worker
    name: Util (External)
    external: true
    properties:
      filepath: packages/repo-tools/src/commands/util.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
    position:
      x: 330
      y: 404
dependencies:
  - from: backstage/packages/repo-tools/commands/repo/schema/openapi/lint
    to: backstage/packages/repo-tools/runner/runner
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/repo-tools/commands/repo/schema/openapi/lint
    to: backstage/packages/repo-tools/openapi/helpers
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/repo-tools/commands/repo/schema/openapi/fuzz
    to: backstage/packages/cli-node/index
    type: direct-call
    description: '@backstage/cli-node'
  - from: backstage/packages/repo-tools/commands/repo/schema/openapi/fuzz
    to: backstage/packages/repo-tools/exec/exec
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/repo-tools/commands/repo/schema/openapi/verify
    to: backstage/packages/cli-common/index
    type: direct-call
    description: '@backstage/cli-common'
  - from: backstage/packages/repo-tools/commands/repo/schema/openapi/verify
    to: backstage/packages/repo-tools/runner/runner
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/repo-tools/commands/repo/schema/openapi/verify
    to: backstage/packages/repo-tools/openapi/constants
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/repo-tools/commands/repo/schema/openapi/verify
    to: backstage/packages/repo-tools/openapi/helpers
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/repo-tools/commands/repo/schema/openapi/diff
    to: backstage/packages/cli-node/index
    type: direct-call
    description: '@backstage/cli-node'
  - from: backstage/packages/repo-tools/commands/repo/schema/openapi/diff
    to: backstage/packages/backend-plugin-api/index
    type: direct-call
    description: '@backstage/backend-plugin-api'
  - from: backstage/packages/repo-tools/commands/repo/schema/openapi/diff
    to: backstage/packages/repo-tools/exec/exec
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/repo-tools/commands/repo/schema/openapi/diff
    to: backstage/packages/cli-common/index
    type: direct-call
    description: '@backstage/cli-common'
  - from: backstage/packages/repo-tools/commands/repo/schema/openapi/diff
    to: backstage/packages/repo-tools/openapi/constants
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/repo-tools/commands/repo/schema/openapi/diff
    to: backstage/packages/repo-tools/commands/util
    type: direct-call
    description: Calls module / service
