apiVersion: blueprint.dev/v4
kind: Diagram
metadata:
  name: Gcp-py-functions Infrastructure
  entityRef: blueprint/gcp-py-functions
  source:
    scannedAtCommit: 5f569592a563374ad00030ffdc8ad87400320ee3
    scanRoot: .
    remoteUrl: https://github.com/pulumi/examples
    defaultBranch: master
spec:
  level: container
  nodes:
    - entityRef: blueprint/gcp-py-functions/gcp-storage-bucket-eta-demo-bucket
      type: container
      name: gcp:storage:Bucket.eta-demo-bucket
      external: false
      properties:
        iac.address: gcp:storage:Bucket.eta_demo_bucket
        iac.provider_type: gcp_storage_bucket
        iac.kind: resource
        filepath: gcp-py-functions/__main__.py
    - entityRef: blueprint/gcp-py-functions/gcp-storage-bucketobject-eta-demo-object
      type: container
      name: gcp:storage:BucketObject.eta-demo-object
      external: false
      properties:
        iac.address: gcp:storage:BucketObject.eta_demo_object
        iac.provider_type: gcp_storage_bucketobject
        iac.kind: resource
        filepath: gcp-py-functions/__main__.py
    - entityRef: blueprint/gcp-py-functions/gcp-cloudfunctions-function-eta-demo-function
      type: serverless-function
      name: gcp:cloudfunctions:Function.eta-demo-function
      external: false
      properties:
        iac.address: gcp:cloudfunctions:Function.eta_demo_function
        iac.provider_type: gcp_cloudfunctions_function
        iac.kind: resource
        filepath: gcp-py-functions/__main__.py
    - entityRef: blueprint/gcp-py-functions/gcp-cloudfunctions-functioniammember-invoker
      type: serverless-function
      name: gcp:cloudfunctions:FunctionIamMember.invoker
      external: false
      properties:
        iac.address: gcp:cloudfunctions:FunctionIamMember.invoker
        iac.provider_type: gcp_cloudfunctions_functioniammember
        iac.kind: resource
        filepath: gcp-py-functions/__main__.py
  dependencies:
    - from: blueprint/gcp-py-functions/gcp-storage-bucketobject-eta-demo-object
      to: blueprint/gcp-py-functions/gcp-storage-bucket-eta-demo-bucket
      type: direct-call
    - from: blueprint/gcp-py-functions/gcp-cloudfunctions-function-eta-demo-function
      to: blueprint/gcp-py-functions/gcp-storage-bucket-eta-demo-bucket
      type: direct-call
    - from: blueprint/gcp-py-functions/gcp-cloudfunctions-function-eta-demo-function
      to: blueprint/gcp-py-functions/gcp-storage-bucketobject-eta-demo-object
      type: direct-call
    - from: blueprint/gcp-py-functions/gcp-cloudfunctions-functioniammember-invoker
      to: blueprint/gcp-py-functions/gcp-storage-bucket-eta-demo-bucket
      type: direct-call
    - from: blueprint/gcp-py-functions/gcp-cloudfunctions-functioniammember-invoker
      to: blueprint/gcp-py-functions/gcp-cloudfunctions-function-eta-demo-function
      type: direct-call
