# git-cliff configuration
# https://git-cliff.org/docs/configuration

[changelog]
header = "# Changelog\n\n"
body = """
{% if version %}\
## v{{ version | trim_start_matches(pat="v") }}
{% else %}\
## Unreleased
{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim }}

{% for commit in commits | unique(attribute="message") -%}
- {% if commit.scope %}*({{ commit.scope }})* {% endif %}{% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}
{% endfor %}
{% endfor %}

"""
trim = true
postprocessors = [
    { pattern = '\n{3,}', replace = "\n\n" },
]

[git]
conventional_commits = true
filter_unconventional = true
require_conventional = false
split_commits = false
filter_tags = "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
ignore_tags = "^web-"
commit_preprocessors = [
    { pattern = '^Merge ', skip = true },
    { pattern = '^Merge pull request', skip = true },
]
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->🚀 Features" },
    { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
    { message = "^refactor|^perf|^improvement", group = "<!-- 2 -->⚙️ Refactoring & Performance" },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore\\(changelog\\)", skip = true },
    { message = "^chore|^ci|^build", group = "<!-- 3 -->🧰 Maintenance & Dependencies" },
    { message = "^docs?", group = "<!-- 4 -->📚 Documentation" },
    { message = "^test", group = "<!-- 5 -->🧪 Testing" },
    { message = "^style", group = "<!-- 6 -->🎨 Styling" },
    { message = "^revert", group = "<!-- 7 -->◀️ Revert" },
    { message = ".*", group = "<!-- 8 -->💼 Other" },
]
filter_commits = false
fail_on_unmatched_commit = false
topo_order_commits = true
sort_commits = "oldest"
