sonar.organization=mzworthington
sonar.projectKey=mzworthington_archlens
sonar.exclusions=.github/workflows/**
sonar.javascript.lcov.reportPaths=app/coverage/lcov.info
sonar.go.coverage.reportPaths=resilience-engine/coverage.out
