apiVersion: blueprint.dev/v4
kind: Diagram
metadata:
  name: Cli-module-info Service Components
  entityRef: blueprint/packages/cli-module-info
  source:
    remoteUrl: https://github.com/backstage/backstage
    defaultBranch: master
    scannedAtCommit: 88690199d13ee94c3285f1ee219ae4339056c133
    scanRoot: .
spec:
  level: component
  nodes:
    - entityRef: blueprint/packages/cli-module-info/info
      type: background-worker
      name: info Service
      isTest: false
      properties:
        filepath: packages/cli-module-info/src/commands/info.ts
        containerId: cli-module-info
        technology: TypeScript Domain Service
        classification: default
      forensics:
        complexity: 30
        loc: 259
        sloc: 194
        churn: 1
        churnByWeek:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 1
          - 0
          - 0
        authorCount: 1
        topAuthorPercent: 1
        authors:
          - email: poldsberg@gmail.com
            commits: 1
        hotspotScore: 0
        classifications:
          - knowledge-silo
        sinceDays: 90
    - entityRef: blueprint/packages/cli-module-info/index
      type: background-worker
      name: index Service
      isTest: false
      properties:
        filepath: packages/cli-module-info/src/index.ts
        containerId: cli-module-info
        technology: TypeScript Domain Service
        classification: default
      forensics:
        complexity: 1
        loc: 29
        sloc: 12
        churn: 1
        churnByWeek:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 1
          - 0
          - 0
        authorCount: 1
        topAuthorPercent: 1
        authors:
          - email: poldsberg@gmail.com
            commits: 1
        hotspotScore: 0
        sinceDays: 90
    - entityRef: blueprint/packages/cli-defaults/index
      type: background-worker
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-defaults/src/index.ts
        containerId: cli-defaults
        technology: TypeScript Domain Service
        classification: default
      x: 100
      'y': -204
    - entityRef: blueprint/packages/cli-common/index
      type: background-worker
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-common/src/index.ts
        containerId: cli-common
        technology: TypeScript Domain Service
        classification: default
      x: -130
      'y': 404
    - entityRef: blueprint/packages/cli-node/index
      type: cache-store
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-node/src/monorepo/index.ts
        containerId: cli-node
        technology: TypeScript Cache Client
        classification: cache-marker
      x: 330
      'y': 404
  dependencies:
    - from: blueprint/packages/cli-defaults/index
      to: blueprint/packages/cli-module-info/index
      type: direct-call
      description: '@backstage/cli-module-info'
    - from: blueprint/packages/cli-module-info/info
      to: blueprint/packages/cli-common/index
      type: direct-call
      description: '@backstage/cli-common'
    - from: blueprint/packages/cli-module-info/info
      to: blueprint/packages/cli-node/index
      type: direct-call
      description: '@backstage/cli-node'
    - from: blueprint/packages/cli-module-info/index
      to: blueprint/packages/cli-node/index
      type: direct-call
      description: '@backstage/cli-node'
