apiVersion: blueprint.dev/v4
kind: Diagram
metadata:
  name: Cli-defaults Service Components
  entityRef: blueprint/packages/cli-defaults
  source:
    remoteUrl: https://github.com/backstage/backstage
    defaultBranch: master
    scannedAtCommit: 88690199d13ee94c3285f1ee219ae4339056c133
    scanRoot: .
spec:
  level: component
  nodes:
    - entityRef: blueprint/packages/cli-defaults/index
      type: background-worker
      name: index Service
      isTest: false
      properties:
        filepath: packages/cli-defaults/src/index.ts
        containerId: cli-defaults
        technology: TypeScript Domain Service
        classification: default
      forensics:
        complexity: 1
        loc: 48
        sloc: 26
        churn: 1
        churnByWeek:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 1
          - 0
          - 0
        authorCount: 1
        topAuthorPercent: 1
        authors:
          - email: poldsberg@gmail.com
            commits: 1
        hotspotScore: 0
        sinceDays: 90
    - entityRef: blueprint/packages/cli-module-actions/index
      type: background-worker
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-module-actions/src/index.ts
        containerId: cli-module-actions
        technology: TypeScript Domain Service
        classification: default
      x: -2430
      'y': 404
    - entityRef: blueprint/packages/cli-module-auth/index
      type: background-worker
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-module-auth/src/index.ts
        containerId: cli-module-auth
        technology: TypeScript Domain Service
        classification: default
      x: -1970
      'y': 404
    - entityRef: blueprint/packages/cli-module-build/index
      type: background-worker
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-module-build/src/lib/runner/index.ts
        containerId: cli-module-build
        technology: TypeScript Domain Service
        classification: default
      x: -1510
      'y': 404
    - entityRef: blueprint/packages/cli-module-config/index
      type: background-worker
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-module-config/src/index.ts
        containerId: cli-module-config
        technology: TypeScript Domain Service
        classification: default
      x: -1050
      'y': 404
    - entityRef: blueprint/packages/cli-module-github/index
      type: gateway-api
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-module-github/src/commands/create-github-app/index.ts
        containerId: cli-module-github
        technology: React Component
        classification: ui-import
      x: -590
      'y': 404
    - entityRef: blueprint/packages/cli-module-info/index
      type: background-worker
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-module-info/src/index.ts
        containerId: cli-module-info
        technology: TypeScript Domain Service
        classification: default
      x: -130
      'y': 404
    - entityRef: blueprint/packages/cli-module-lint/index
      type: background-worker
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-module-lint/src/index.ts
        containerId: cli-module-lint
        technology: TypeScript Domain Service
        classification: default
      x: 330
      'y': 404
    - entityRef: blueprint/packages/cli-module-maintenance/index
      type: background-worker
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-module-maintenance/src/index.ts
        containerId: cli-module-maintenance
        technology: TypeScript Domain Service
        classification: default
      x: 790
      'y': 404
    - entityRef: blueprint/packages/cli-module-migrate/index
      type: background-worker
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-module-migrate/src/index.ts
        containerId: cli-module-migrate
        technology: TypeScript Domain Service
        classification: default
      x: 1250
      'y': 404
    - entityRef: blueprint/packages/cli-module-new/index
      type: background-worker
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-module-new/templates/frontend-plugin/dev/index.tsx
        containerId: cli-module-new
        technology: TypeScript Domain Service
        classification: default
      x: 1710
      'y': 404
    - entityRef: blueprint/packages/cli-module-test-jest/index
      type: background-worker
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-module-test-jest/src/index.ts
        containerId: cli-module-test-jest
        technology: TypeScript Domain Service
        classification: default
      x: 2170
      'y': 404
    - entityRef: blueprint/packages/cli-module-translations/index
      type: background-worker
      name: index Service (External)
      external: true
      properties:
        filepath: packages/cli-module-translations/src/index.ts
        containerId: cli-module-translations
        technology: TypeScript Domain Service
        classification: default
      x: 2630
      'y': 404
  dependencies:
    - from: blueprint/packages/cli-defaults/index
      to: blueprint/packages/cli-module-actions/index
      type: direct-call
      description: '@backstage/cli-module-actions'
    - from: blueprint/packages/cli-defaults/index
      to: blueprint/packages/cli-module-auth/index
      type: direct-call
      description: '@backstage/cli-module-auth'
    - from: blueprint/packages/cli-defaults/index
      to: blueprint/packages/cli-module-build/index
      type: direct-call
      description: '@backstage/cli-module-build'
    - from: blueprint/packages/cli-defaults/index
      to: blueprint/packages/cli-module-config/index
      type: direct-call
      description: '@backstage/cli-module-config'
    - from: blueprint/packages/cli-defaults/index
      to: blueprint/packages/cli-module-github/index
      type: direct-call
      description: '@backstage/cli-module-github'
    - from: blueprint/packages/cli-defaults/index
      to: blueprint/packages/cli-module-info/index
      type: direct-call
      description: '@backstage/cli-module-info'
    - from: blueprint/packages/cli-defaults/index
      to: blueprint/packages/cli-module-lint/index
      type: direct-call
      description: '@backstage/cli-module-lint'
    - from: blueprint/packages/cli-defaults/index
      to: blueprint/packages/cli-module-maintenance/index
      type: direct-call
      description: '@backstage/cli-module-maintenance'
    - from: blueprint/packages/cli-defaults/index
      to: blueprint/packages/cli-module-migrate/index
      type: direct-call
      description: '@backstage/cli-module-migrate'
    - from: blueprint/packages/cli-defaults/index
      to: blueprint/packages/cli-module-new/index
      type: direct-call
      description: '@backstage/cli-module-new'
    - from: blueprint/packages/cli-defaults/index
      to: blueprint/packages/cli-module-test-jest/index
      type: direct-call
      description: '@backstage/cli-module-test-jest'
    - from: blueprint/packages/cli-defaults/index
      to: blueprint/packages/cli-module-translations/index
      type: direct-call
      description: '@backstage/cli-module-translations'
