version: https://archlens.dev/schemas/v4/blueprint.schema.json
level: container
metadata:
  entityRef: infrastructure/gcp-py-gke
  name: Gcp-py-gke Infrastructure
  source:
    scannedAtCommit: 63ae0bceb16a3a7903ec7e6c25c86bbd556e6065
    scanRoot: .
    remoteUrl: https://github.com/pulumi/examples
    defaultBranch: master
nodes:
  - entityRef: infrastructure/gcp-py-gke/gcp-container-cluster-gke-cluster
    type: microservice
    name: gcp:container:Cluster.gke-cluster
    external: false
    properties:
      iac.address: gcp:container:Cluster.gke-cluster
      iac.provider_type: gcp_container_cluster
      iac.kind: resource
      filepath: gcp-py-gke/__main__.py
  - entityRef: infrastructure/gcp-py-gke/kubernetes-apps-v1-deployment-canary
    type: container
    name: kubernetes:apps:v1.Deployment.canary
    external: false
    properties:
      iac.address: kubernetes:apps:v1.Deployment.canary
      iac.provider_type: kubernetes_apps_v1.deployment
      iac.kind: resource
      filepath: gcp-py-gke/__main__.py
dependencies: []
