apiVersion: blueprint.dev/v4
kind: Diagram
metadata:
  name: Gcp-py-instance-nginx Service Components
  entityRef: blueprint/helloworld/gcp-py-instance-nginx
  source:
    scannedAtCommit: 5f569592a563374ad00030ffdc8ad87400320ee3
    scanRoot: .
    remoteUrl: https://github.com/pulumi/examples
    defaultBranch: master
spec:
  level: component
  nodes:
    - entityRef: blueprint/helloworld/gcp-py-instance-nginx/__main__
      type: background-worker
      name: __main__ Service
      isTest: false
      properties:
        filepath: gcp-py-instance-nginx/__main__.py
        containerId: gcp-py-instance-nginx
        technology: Python Domain Service
        classification: default
  dependencies: []
