apiVersion: blueprint.dev/v4
kind: Diagram
metadata:
  name: Gcp-py-serverless-raw Service Components
  entityRef: blueprint/helloworld/gcp-py-serverless-raw
  source:
    scannedAtCommit: 5f569592a563374ad00030ffdc8ad87400320ee3
    scanRoot: .
    remoteUrl: https://github.com/pulumi/examples
    defaultBranch: master
spec:
  level: component
  nodes:
    - entityRef: blueprint/helloworld/gcp-py-serverless-raw/__main__
      type: background-worker
      name: __main__ Service
      isTest: false
      properties:
        filepath: gcp-py-serverless-raw/__main__.py
        containerId: gcp-py-serverless-raw
        technology: Python Domain Service
        classification: default
  dependencies: []
