apiVersion: blueprint.dev/v4
kind: Diagram
metadata:
  name: Pythonfunc Service Components
  entityRef: blueprint/helloworld/pythonfunc
  source:
    scannedAtCommit: 5f569592a563374ad00030ffdc8ad87400320ee3
    scanRoot: .
    remoteUrl: https://github.com/pulumi/examples
    defaultBranch: master
spec:
  level: component
  nodes:
    - entityRef: blueprint/helloworld/pythonfunc/main
      type: background-worker
      name: main Service
      isTest: false
      properties:
        filepath: gcp-py-serverless-raw/pythonfunc/main.py
        containerId: pythonfunc
        technology: Python Domain Service
        classification: default
  dependencies: []
