version: https://archlens.dev/schemas/v4/blueprint.schema.json
level: container
metadata:
  entityRef: blueprint/infrastructure
  name: Infrastructure Infrastructure
  source:
    scannedAtCommit: d4669ca8eb109a37f6c19ab8fb9487ab7521a9ba
    scanRoot: .
    remoteUrl: https://github.com/terraform-aws-modules/terraform-aws-eks
    defaultBranch: master
nodes:
  - entityRef: blueprint/infrastructure/aws-eks-cluster-this
    type: microservice
    name: aws-eks-cluster.this
    external: false
    properties:
      iac.address: aws_eks_cluster.this
      iac.provider_type: aws_eks_cluster
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-ec2-tag-cluster-primary-security-group
    type: container
    name: aws-ec2-tag.cluster-primary-security-group
    external: false
    properties:
      iac.address: aws_ec2_tag.cluster_primary_security_group
      iac.provider_type: aws_ec2_tag
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-cloudwatch-log-group-this
    type: container
    name: aws-cloudwatch-log-group.this
    external: false
    properties:
      iac.address: aws_cloudwatch_log_group.this
      iac.provider_type: aws_cloudwatch_log_group
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-eks-access-entry-this
    type: microservice
    name: aws-eks-access-entry.this
    external: false
    properties:
      iac.address: aws_eks_access_entry.this
      iac.provider_type: aws_eks_access_entry
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-eks-access-policy-association-this
    type: microservice
    name: aws-eks-access-policy-association.this
    external: false
    properties:
      iac.address: aws_eks_access_policy_association.this
      iac.provider_type: aws_eks_access_policy_association
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-security-group-cluster
    type: container
    name: aws-security-group.cluster
    external: false
    properties:
      iac.address: aws_security_group.cluster
      iac.provider_type: aws_security_group
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-security-group-rule-cluster
    type: container
    name: aws-security-group-rule.cluster
    external: false
    properties:
      iac.address: aws_security_group_rule.cluster
      iac.provider_type: aws_security_group_rule
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-iam-openid-connect-provider-oidc-provider
    type: container
    name: aws-iam-openid-connect-provider.oidc-provider
    external: false
    properties:
      iac.address: aws_iam_openid_connect_provider.oidc_provider
      iac.provider_type: aws_iam_openid_connect_provider
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-iam-role-this
    type: container
    name: aws-iam-role.this
    external: false
    properties:
      iac.address: aws_iam_role.this
      iac.provider_type: aws_iam_role
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-iam-role-eks-auto
    type: container
    name: aws-iam-role.eks-auto
    external: false
    properties:
      iac.address: aws_iam_role.eks_auto
      iac.provider_type: aws_iam_role
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-iam-role-policy-attachment-this
    type: container
    name: aws-iam-role-policy-attachment.this
    external: false
    properties:
      iac.address: aws_iam_role_policy_attachment.this
      iac.provider_type: aws_iam_role_policy_attachment
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-iam-role-policy-attachment-additional
    type: container
    name: aws-iam-role-policy-attachment.additional
    external: false
    properties:
      iac.address: aws_iam_role_policy_attachment.additional
      iac.provider_type: aws_iam_role_policy_attachment
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-iam-role-policy-attachment-cluster-encryption
    type: container
    name: aws-iam-role-policy-attachment.cluster-encryption
    external: false
    properties:
      iac.address: aws_iam_role_policy_attachment.cluster_encryption
      iac.provider_type: aws_iam_role_policy_attachment
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-iam-role-policy-attachment-custom
    type: container
    name: aws-iam-role-policy-attachment.custom
    external: false
    properties:
      iac.address: aws_iam_role_policy_attachment.custom
      iac.provider_type: aws_iam_role_policy_attachment
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-iam-role-policy-attachment-eks-auto
    type: container
    name: aws-iam-role-policy-attachment.eks-auto
    external: false
    properties:
      iac.address: aws_iam_role_policy_attachment.eks_auto
      iac.provider_type: aws_iam_role_policy_attachment
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-iam-role-policy-attachment-eks-auto-additional
    type: container
    name: aws-iam-role-policy-attachment.eks-auto-additional
    external: false
    properties:
      iac.address: aws_iam_role_policy_attachment.eks_auto_additional
      iac.provider_type: aws_iam_role_policy_attachment
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-iam-policy-cluster-encryption
    type: container
    name: aws-iam-policy.cluster-encryption
    external: false
    properties:
      iac.address: aws_iam_policy.cluster_encryption
      iac.provider_type: aws_iam_policy
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-iam-policy-custom
    type: container
    name: aws-iam-policy.custom
    external: false
    properties:
      iac.address: aws_iam_policy.custom
      iac.provider_type: aws_iam_policy
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-eks-addon-this
    type: microservice
    name: aws-eks-addon.this
    external: false
    properties:
      iac.address: aws_eks_addon.this
      iac.provider_type: aws_eks_addon
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-eks-addon-before-compute
    type: microservice
    name: aws-eks-addon.before-compute
    external: false
    properties:
      iac.address: aws_eks_addon.before_compute
      iac.provider_type: aws_eks_addon
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/aws-eks-identity-provider-config-this
    type: microservice
    name: aws-eks-identity-provider-config.this
    external: false
    properties:
      iac.address: aws_eks_identity_provider_config.this
      iac.provider_type: aws_eks_identity_provider_config
      iac.kind: resource
      filepath: main.tf
  - entityRef: blueprint/infrastructure/data-aws-partition-current
    type: container
    name: data.aws-partition.current
    external: true
    properties:
      iac.address: data.aws_partition.current
      iac.provider_type: aws_partition
      iac.kind: data
      filepath: main.tf
  - entityRef: blueprint/infrastructure/data-aws-caller-identity-current
    type: container
    name: data.aws-caller-identity.current
    external: true
    properties:
      iac.address: data.aws_caller_identity.current
      iac.provider_type: aws_caller_identity
      iac.kind: data
      filepath: main.tf
  - entityRef: blueprint/infrastructure/data-aws-iam-session-context-current
    type: container
    name: data.aws-iam-session-context.current
    external: true
    properties:
      iac.address: data.aws_iam_session_context.current
      iac.provider_type: aws_iam_session_context
      iac.kind: data
      filepath: main.tf
  - entityRef: blueprint/infrastructure/data-tls-certificate-this
    type: container
    name: data.tls-certificate.this
    external: true
    properties:
      iac.address: data.tls_certificate.this
      iac.provider_type: tls_certificate
      iac.kind: data
      filepath: main.tf
  - entityRef: blueprint/infrastructure/data-aws-iam-policy-document-assume-role-policy
    type: container
    name: data.aws-iam-policy-document.assume-role-policy
    external: true
    properties:
      iac.address: data.aws_iam_policy_document.assume_role_policy
      iac.provider_type: aws_iam_policy_document
      iac.kind: data
      filepath: main.tf
  - entityRef: blueprint/infrastructure/data-aws-iam-policy-document-custom
    type: container
    name: data.aws-iam-policy-document.custom
    external: true
    properties:
      iac.address: data.aws_iam_policy_document.custom
      iac.provider_type: aws_iam_policy_document
      iac.kind: data
      filepath: main.tf
  - entityRef: blueprint/infrastructure/data-aws-iam-policy-document-node-assume-role-policy
    type: container
    name: data.aws-iam-policy-document.node-assume-role-policy
    external: true
    properties:
      iac.address: data.aws_iam_policy_document.node_assume_role_policy
      iac.provider_type: aws_iam_policy_document
      iac.kind: data
      filepath: main.tf
  - entityRef: blueprint/infrastructure/data-aws-eks-addon-version-this
    type: microservice
    name: data.aws-eks-addon-version.this
    external: true
    properties:
      iac.address: data.aws_eks_addon_version.this
      iac.provider_type: aws_eks_addon_version
      iac.kind: data
      filepath: main.tf
  - entityRef: blueprint/infrastructure/module-kms
    type: container
    name: module.kms
    external: true
    properties:
      iac.address: module.kms
      iac.provider_type: module
      iac.kind: module
      iac.source: terraform-aws-modules/kms/aws
      filepath: main.tf
  - entityRef: blueprint/infrastructure/time-sleep-this
    type: container
    name: time-sleep.this
    external: false
    properties:
      iac.address: time_sleep.this
      iac.provider_type: time_sleep
      iac.kind: resource
      filepath: node_groups.tf
  - entityRef: blueprint/infrastructure/aws-iam-policy-cni-ipv6-policy
    type: container
    name: aws-iam-policy.cni-ipv6-policy
    external: false
    properties:
      iac.address: aws_iam_policy.cni_ipv6_policy
      iac.provider_type: aws_iam_policy
      iac.kind: resource
      filepath: node_groups.tf
  - entityRef: blueprint/infrastructure/aws-security-group-node
    type: container
    name: aws-security-group.node
    external: false
    properties:
      iac.address: aws_security_group.node
      iac.provider_type: aws_security_group
      iac.kind: resource
      filepath: node_groups.tf
  - entityRef: blueprint/infrastructure/aws-security-group-rule-node
    type: container
    name: aws-security-group-rule.node
    external: false
    properties:
      iac.address: aws_security_group_rule.node
      iac.provider_type: aws_security_group_rule
      iac.kind: resource
      filepath: node_groups.tf
  - entityRef: blueprint/infrastructure/data-aws-iam-policy-document-cni-ipv6-policy
    type: container
    name: data.aws-iam-policy-document.cni-ipv6-policy
    external: true
    properties:
      iac.address: data.aws_iam_policy_document.cni_ipv6_policy
      iac.provider_type: aws_iam_policy_document
      iac.kind: data
      filepath: node_groups.tf
  - entityRef: blueprint/infrastructure/module-fargate-profile
    type: container
    name: module.fargate-profile
    external: false
    properties:
      iac.address: module.fargate_profile
      iac.provider_type: module
      iac.kind: module
      iac.source: ./modules/fargate-profile
      filepath: node_groups.tf
  - entityRef: blueprint/infrastructure/module-eks-managed-node-group
    type: container
    name: module.eks-managed-node-group
    external: false
    properties:
      iac.address: module.eks_managed_node_group
      iac.provider_type: module
      iac.kind: module
      iac.source: ./modules/eks-managed-node-group
      filepath: node_groups.tf
  - entityRef: blueprint/infrastructure/module-self-managed-node-group
    type: container
    name: module.self-managed-node-group
    external: false
    properties:
      iac.address: module.self_managed_node_group
      iac.provider_type: module
      iac.kind: module
      iac.source: ./modules/self-managed-node-group
      filepath: node_groups.tf
dependencies:
  - from: blueprint/infrastructure/aws-eks-cluster-this
    to: blueprint/infrastructure/aws-iam-role-eks-auto
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-cluster-this
    to: blueprint/infrastructure/module-kms
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-cluster-this
    to: blueprint/infrastructure/aws-iam-role-policy-attachment-this
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-cluster-this
    to: blueprint/infrastructure/aws-security-group-rule-cluster
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-cluster-this
    to: blueprint/infrastructure/aws-security-group-rule-node
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-cluster-this
    to: blueprint/infrastructure/aws-cloudwatch-log-group-this
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-cluster-this
    to: blueprint/infrastructure/aws-iam-policy-cni-ipv6-policy
    type: direct-call
  - from: blueprint/infrastructure/aws-ec2-tag-cluster-primary-security-group
    to: blueprint/infrastructure/aws-eks-cluster-this
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-access-entry-this
    to: blueprint/infrastructure/aws-eks-cluster-this
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-access-policy-association-this
    to: blueprint/infrastructure/aws-eks-cluster-this
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-access-policy-association-this
    to: blueprint/infrastructure/aws-eks-access-entry-this
    type: direct-call
  - from: blueprint/infrastructure/aws-security-group-rule-cluster
    to: blueprint/infrastructure/aws-security-group-cluster
    type: direct-call
  - from: blueprint/infrastructure/aws-iam-openid-connect-provider-oidc-provider
    to: blueprint/infrastructure/aws-eks-cluster-this
    type: direct-call
  - from: blueprint/infrastructure/aws-iam-role-this
    to: blueprint/infrastructure/data-aws-iam-policy-document-assume-role-policy
    type: direct-call
  - from: blueprint/infrastructure/aws-iam-role-eks-auto
    to: blueprint/infrastructure/data-aws-iam-policy-document-node-assume-role-policy
    type: direct-call
  - from: blueprint/infrastructure/aws-iam-role-policy-attachment-this
    to: blueprint/infrastructure/aws-iam-role-this
    type: direct-call
  - from: blueprint/infrastructure/aws-iam-role-policy-attachment-additional
    to: blueprint/infrastructure/aws-iam-role-this
    type: direct-call
  - from: blueprint/infrastructure/aws-iam-role-policy-attachment-cluster-encryption
    to: blueprint/infrastructure/aws-iam-policy-cluster-encryption
    type: direct-call
  - from: blueprint/infrastructure/aws-iam-role-policy-attachment-cluster-encryption
    to: blueprint/infrastructure/aws-iam-role-this
    type: direct-call
  - from: blueprint/infrastructure/aws-iam-role-policy-attachment-custom
    to: blueprint/infrastructure/aws-iam-policy-custom
    type: direct-call
  - from: blueprint/infrastructure/aws-iam-role-policy-attachment-custom
    to: blueprint/infrastructure/aws-iam-role-this
    type: direct-call
  - from: blueprint/infrastructure/aws-iam-role-policy-attachment-eks-auto
    to: blueprint/infrastructure/aws-iam-role-eks-auto
    type: direct-call
  - from: blueprint/infrastructure/aws-iam-role-policy-attachment-eks-auto-additional
    to: blueprint/infrastructure/aws-iam-role-eks-auto
    type: direct-call
  - from: blueprint/infrastructure/aws-iam-policy-cluster-encryption
    to: blueprint/infrastructure/module-kms
    type: direct-call
  - from: blueprint/infrastructure/aws-iam-policy-custom
    to: blueprint/infrastructure/data-aws-iam-policy-document-custom
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-addon-this
    to: blueprint/infrastructure/aws-eks-cluster-this
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-addon-this
    to: blueprint/infrastructure/data-aws-eks-addon-version-this
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-addon-this
    to: blueprint/infrastructure/module-fargate-profile
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-addon-this
    to: blueprint/infrastructure/module-eks-managed-node-group
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-addon-this
    to: blueprint/infrastructure/module-self-managed-node-group
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-addon-before-compute
    to: blueprint/infrastructure/aws-eks-cluster-this
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-addon-before-compute
    to: blueprint/infrastructure/data-aws-eks-addon-version-this
    type: direct-call
  - from: blueprint/infrastructure/aws-eks-identity-provider-config-this
    to: blueprint/infrastructure/aws-eks-cluster-this
    type: direct-call
  - from: blueprint/infrastructure/data-aws-iam-session-context-current
    to: blueprint/infrastructure/data-aws-caller-identity-current
    type: direct-call
  - from: blueprint/infrastructure/data-tls-certificate-this
    to: blueprint/infrastructure/aws-eks-cluster-this
    type: direct-call
  - from: blueprint/infrastructure/data-aws-eks-addon-version-this
    to: blueprint/infrastructure/aws-eks-cluster-this
    type: direct-call
  - from: blueprint/infrastructure/module-kms
    to: blueprint/infrastructure/data-aws-iam-session-context-current
    type: direct-call
  - from: blueprint/infrastructure/time-sleep-this
    to: blueprint/infrastructure/aws-eks-cluster-this
    type: direct-call
  - from: blueprint/infrastructure/aws-iam-policy-cni-ipv6-policy
    to: blueprint/infrastructure/data-aws-iam-policy-document-cni-ipv6-policy
    type: direct-call
  - from: blueprint/infrastructure/aws-security-group-rule-node
    to: blueprint/infrastructure/aws-security-group-node
    type: direct-call
  - from: blueprint/infrastructure/module-fargate-profile
    to: blueprint/infrastructure/time-sleep-this
    type: direct-call
  - from: blueprint/infrastructure/module-eks-managed-node-group
    to: blueprint/infrastructure/time-sleep-this
    type: direct-call
  - from: blueprint/infrastructure/module-eks-managed-node-group
    to: blueprint/infrastructure/aws-eks-cluster-this
    type: direct-call
  - from: blueprint/infrastructure/module-self-managed-node-group
    to: blueprint/infrastructure/time-sleep-this
    type: direct-call
  - from: blueprint/infrastructure/module-self-managed-node-group
    to: blueprint/infrastructure/aws-eks-cluster-this
    type: direct-call
