version: https://archlens.dev/schemas/v4/blueprint.schema.json
level: context
metadata:
  entityRef: infrastructure
  name: Application
  source:
    scannedAtCommit: c191f7bcb0fa786b68c7b3904b6f3bbb90881fc6
    scanRoot: .
    remoteUrl: https://github.com/futurice/terraform-examples
    defaultBranch: master
nodes:
  - entityRef: application/gpio-build-monitor
    type: software-system
    name: Gpio Build Monitor System
    properties:
      rootPath: ''
      productId: gpio-build-monitor
    forensics:
      complexity: 12
      complexityPeak: 12
      cognitiveComplexity: 50
      churn: 23
      lineChurn: 1763
      churn30: 23
      churn365: 23
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 23
        - 0
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: matt@siliconpanda.com
          commits: 23
      hotspotScore: 0.6218487394957983
      classifications:
        - hotspot
        - knowledge-silo
      sinceDays: 365
      fileCount: 30
      hotspotCount: 1
      knowledgeSiloCount: 1
  - entityRef: infrastructure/user
    type: person
    name: User
    properties:
      role: context-actor
  - entityRef: infrastructure/terraform-examples
    type: group
    name: Terraform Examples System
    properties:
      rootPath: ''
      productId: terraform-examples
    forensics:
      complexity: 1
      complexityPeak: 1
      churn: 0
      churn30: 0
      churn365: 0
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
      authorCount: 0
      hotspotScore: 0
      sinceDays: 365
      fileCount: 1
      hotspotCount: 0
      knowledgeSiloCount: 0
  - entityRef: infrastructure/aws-lambda-api
    type: software-system
    name: Aws-lambda-api System
    parentEntityRef: infrastructure/terraform-examples
    properties:
      rootPath: aws/aws_lambda_api
      productId: terraform-examples
  - entityRef: infrastructure/aws-reverse-proxy
    type: software-system
    name: Aws-reverse-proxy System
    parentEntityRef: infrastructure/terraform-examples
    properties:
      rootPath: aws/aws_reverse_proxy
      productId: terraform-examples
  - entityRef: infrastructure/aws-domain-redirect
    type: software-system
    name: Aws-domain-redirect System
    parentEntityRef: infrastructure/terraform-examples
    properties:
      rootPath: aws/aws_domain_redirect
      productId: terraform-examples
dependencies:
  - from: infrastructure/user
    to: application/gpio-build-monitor
    type: direct-call
    description: Uses
  - from: infrastructure/user
    to: infrastructure/terraform-examples
    type: direct-call
    description: Uses
