apiVersion: blueprint.dev/v4
kind: Diagram
metadata:
  name: Aws-domain-redirect Infrastructure
  entityRef: blueprint/aws-domain-redirect
  source:
    scannedAtCommit: c191f7bcb0fa786b68c7b3904b6f3bbb90881fc6
    scanRoot: .
    remoteUrl: https://github.com/futurice/terraform-examples
    defaultBranch: master
spec:
  level: container
  nodes:
    - entityRef: blueprint/aws-domain-redirect/module-aws-reverse-proxy
      type: container
      name: module.aws-reverse-proxy
      external: true
      properties:
        iac.address: module.aws_reverse_proxy
        iac.provider_type: module
        iac.kind: module
        iac.source: git::ssh://git@github.com/futurice/terraform-utils.git//aws_reverse_proxy?ref=v11.0
        filepath: aws/aws_domain_redirect/main.tf
  dependencies: []
