version: https://archlens.dev/schemas/v4/blueprint.schema.json
level: component
metadata:
  entityRef: blueprint/app/designer/application
  name: Application Components
  source:
    remoteUrl: https://github.com/mzworthington/blueprint
    defaultBranch: main
    scannedAtCommit: ffbf467109f8056fcf1b6dd3a78fb6dbc0074362
    scanRoot: .
nodes:
  - entityRef: blueprint/app/designer/application/context
    type: gateway-api
    name: Context
    isTest: false
    properties:
      containerId: designer
      technology: React Component
      classification: ui-import
    forensics:
      complexity: 2
      complexityPeak: 2
      cognitiveComplexity: 1
      loc: 181
      sloc: 155
      churn: 12
      lineChurn: 354
      churn30: 12
      churn365: 12
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 3
        - 3
        - 6
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: matt@siliconpanda.com
          commits: 12
      hotspotScore: 0.0016581585125013973
      sinceDays: 365
      fileCount: 2
      hotspotCount: 0
      knowledgeSiloCount: 0
  - entityRef: blueprint/app/designer/application/layout
    type: background-worker
    name: Layout
    isTest: false
    properties:
      containerId: designer
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 1
      loc: 198
      sloc: 154
      churn: 10
      lineChurn: 207
      churn30: 10
      churn365: 10
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 4
        - 4
        - 2
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: matt@siliconpanda.com
          commits: 10
      hotspotScore: 0.00004968265205996696
      sinceDays: 365
      fileCount: 5
      hotspotCount: 0
      knowledgeSiloCount: 0
  - entityRef: blueprint/app/designer/application/workspace
    type: background-worker
    name: Workspace
    isTest: false
    properties:
      containerId: designer
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 0
      loc: 195
      sloc: 168
      churn: 0
      churn30: 0
      churn365: 0
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
      authorCount: 0
      hotspotScore: 0
      sinceDays: 365
      fileCount: 2
      hotspotCount: 0
      knowledgeSiloCount: 0
  - entityRef: blueprint/app/designer/application/navigation
    type: background-worker
    name: Navigation
    isTest: false
    properties:
      containerId: designer
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 2
      complexityPeak: 2
      cognitiveComplexity: 1
      loc: 99
      sloc: 74
      churn: 8
      lineChurn: 218
      churn30: 8
      churn365: 8
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 4
        - 4
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: matt@siliconpanda.com
          commits: 8
      hotspotScore: 0.0004502490342934505
      sinceDays: 365
      fileCount: 3
      hotspotCount: 0
      knowledgeSiloCount: 0
  - entityRef: blueprint/app/designer/application/forensics
    type: gateway-api
    name: Forensics
    isTest: false
    properties:
      containerId: designer
      technology: React Component
      classification: ui-import
    forensics:
      complexity: 19
      complexityPeak: 19
      cognitiveComplexity: 139
      loc: 5677
      sloc: 4906
      churn: 125
      lineChurn: 6273
      churn30: 125
      churn365: 125
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 24
        - 20
        - 81
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: matt@siliconpanda.com
          commits: 125
      hotspotScore: 0.02418924122169641
      classifications:
        - knowledge-silo
      sinceDays: 365
      fileCount: 48
      hotspotCount: 0
      knowledgeSiloCount: 6
  - entityRef: blueprint/app/designer/application/canvas
    type: gateway-api
    name: Canvas
    isTest: false
    properties:
      filepath: app/packages/designer/src/application/canvas/exportCanvasImage.ts
      containerId: designer
      technology: React Component
      classification: ui-import
    forensics:
      complexity: 0
      loc: 64
      sloc: 50
      churn: 1
      lineChurn: 63
      churn30: 1
      churn365: 1
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 1
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: matt@siliconpanda.com
          commits: 1
      hotspotScore: 0
      sinceDays: 365
  - entityRef: blueprint/app/designer/application/recommendations
    type: background-worker
    name: Recommendations
    isTest: false
    properties:
      containerId: designer
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 0
      loc: 971
      sloc: 855
      churn: 10
      lineChurn: 1021
      churn30: 10
      churn365: 10
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 10
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: matt@siliconpanda.com
          commits: 10
      hotspotScore: 0
      sinceDays: 365
      fileCount: 8
      hotspotCount: 0
      knowledgeSiloCount: 0
  - entityRef: blueprint/app/designer/application/search
    type: background-worker
    name: Search
    isTest: false
    properties:
      containerId: designer
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 16
      complexityPeak: 16
      cognitiveComplexity: 80
      loc: 230
      sloc: 200
      churn: 6
      lineChurn: 284
      churn30: 6
      churn365: 6
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 4
        - 2
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: matt@siliconpanda.com
          commits: 6
      hotspotScore: 0.004968265205996696
      classifications:
        - knowledge-silo
      sinceDays: 365
      fileCount: 2
      hotspotCount: 0
      knowledgeSiloCount: 1
  - entityRef: blueprint/app/designer/application/resilience
    type: background-worker
    name: Resilience
    isTest: false
    properties:
      containerId: designer
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 10
      complexityPeak: 10
      cognitiveComplexity: 13
      loc: 1046
      sloc: 905
      churn: 25
      lineChurn: 1063
      churn30: 25
      churn365: 25
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 6
        - 19
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: matt@siliconpanda.com
          commits: 25
      hotspotScore: 0.004409335370322068
      classifications:
        - knowledge-silo
      sinceDays: 365
      fileCount: 13
      hotspotCount: 0
      knowledgeSiloCount: 1
  - entityRef: blueprint/app/designer/application/pwa
    type: background-worker
    name: Pwa
    isTest: false
    properties:
      containerId: designer
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 0
      loc: 92
      sloc: 74
      churn: 2
      lineChurn: 61
      churn30: 2
      churn365: 2
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: matt@siliconpanda.com
          commits: 2
      hotspotScore: 0
      sinceDays: 365
      fileCount: 2
      hotspotCount: 0
      knowledgeSiloCount: 0
  - entityRef: blueprint/app/designer/application/parsing
    type: background-worker
    name: Parsing
    isTest: false
    properties:
      containerId: designer
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 1
      complexityPeak: 1
      loc: 344
      sloc: 283
      churn: 11
      lineChurn: 356
      churn30: 11
      churn365: 11
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 6
        - 5
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: matt@siliconpanda.com
          commits: 11
      hotspotScore: 0.00013662729316490913
      sinceDays: 365
      fileCount: 6
      hotspotCount: 0
      knowledgeSiloCount: 0
  - entityRef: blueprint/app/designer/application/store
    type: background-worker
    name: Store
    isTest: false
    properties:
      containerId: designer
      technology: TypeScript Domain Service
      classification: default
  - entityRef: blueprint/app/designer/application/fetch-source-file-content-test
    type: background-worker
    name: FetchSourceFileContent
    isTest: true
    properties:
      filepath: app/packages/designer/src/application/source/fetchSourceFileContent.test.ts
      containerId: designer
      technology: TypeScript Domain Service
      classification: default
  - entityRef: blueprint/app/designer/application/fetch-source-file-content
    type: background-worker
    name: FetchSourceFileContent
    isTest: false
    properties:
      filepath: app/packages/designer/src/application/source/fetchSourceFileContent.ts
      containerId: designer
      technology: TypeScript Domain Service
      classification: default
  - entityRef: blueprint/app/core/index
    type: background-worker
    name: Index (External)
    external: true
    properties:
      filepath: app/packages/core/src/index.ts
      containerId: core
      technology: TypeScript Domain Service
      classification: default
    position:
      x: 100
      y: 404
dependencies:
  - from: blueprint/app/designer/application/fetch-source-file-content-test
    to: blueprint/app/designer/application/fetch-source-file-content
    type: direct-call
    description: Calls module / service
  - from: blueprint/app/designer/application/fetch-source-file-content-test
    to: blueprint/app/core/index
    type: direct-call
    description: '@archlens/core'
  - from: blueprint/app/designer/application/fetch-source-file-content
    to: blueprint/app/core/index
    type: direct-call
    description: '@archlens/core'
  - from: blueprint/app/designer/application/store
    to: blueprint/app/designer/application/store/states/ui-state
    type: direct-call
    description: Calls module / service
  - from: blueprint/app/designer/application/store
    to: blueprint/app/designer/application/store/states/diagram-state
    type: direct-call
    description: Calls module / service
  - from: blueprint/app/designer/application/store
    to: blueprint/app/designer/application/store/states/io-state
    type: direct-call
    description: Calls module / service
  - from: blueprint/app/designer/application/store
    to: blueprint/app/designer/application/store/states/resilience-state
    type: direct-call
    description: Calls module / service
  - from: blueprint/app/designer/application/store
    to: blueprint/app/designer/application/store/states/trace-lens-state
    type: direct-call
    description: Calls module / service
  - from: blueprint/app/designer/application/store
    to: blueprint/app/designer/application/store/layout-utils
    type: read-write
    description: Queries datastore records
  - from: blueprint/app/designer/application/store
    to: blueprint/app/core/index
    type: direct-call
    description: '@archlens/core'
  - from: blueprint/app/designer/application/store
    to: blueprint/app/designer/application/store/golden-paths-sample
    type: read-write
    description: Queries datastore records
