version: https://archlens.dev/schemas/v4/blueprint.schema.json
level: container
metadata:
  entityRef: infrastructure/gcp-py-serverless-raw
  name: Gcp-py-serverless-raw Infrastructure
  source:
    scannedAtCommit: 63ae0bceb16a3a7903ec7e6c25c86bbd556e6065
    scanRoot: .
    remoteUrl: https://github.com/pulumi/examples
    defaultBranch: master
nodes:
  - entityRef: infrastructure/gcp-py-serverless-raw/gcp-storage-bucket-bucket
    type: container
    name: gcp:storage:Bucket.bucket
    external: false
    properties:
      iac.address: gcp:storage:Bucket.bucket
      iac.provider_type: gcp_storage_bucket
      iac.kind: resource
      filepath: gcp-py-serverless-raw/__main__.py
  - entityRef: infrastructure/gcp-py-serverless-raw/gcp-storage-bucketobject-python-zip
    type: container
    name: gcp:storage:BucketObject.python-zip
    external: false
    properties:
      iac.address: gcp:storage:BucketObject.python-zip
      iac.provider_type: gcp_storage_bucketobject
      iac.kind: resource
      filepath: gcp-py-serverless-raw/__main__.py
  - entityRef: infrastructure/gcp-py-serverless-raw/gcp-cloudfunctions-function-python-func
    type: serverless-function
    name: gcp:cloudfunctions:Function.python-func
    external: false
    properties:
      iac.address: gcp:cloudfunctions:Function.python-func
      iac.provider_type: gcp_cloudfunctions_function
      iac.kind: resource
      filepath: gcp-py-serverless-raw/__main__.py
  - entityRef: infrastructure/gcp-py-serverless-raw/gcp-cloudfunctions-functioniammember-py-invoker
    type: serverless-function
    name: gcp:cloudfunctions:FunctionIamMember.py-invoker
    external: false
    properties:
      iac.address: gcp:cloudfunctions:FunctionIamMember.py-invoker
      iac.provider_type: gcp_cloudfunctions_functioniammember
      iac.kind: resource
      filepath: gcp-py-serverless-raw/__main__.py
  - entityRef: infrastructure/gcp-py-serverless-raw/gcp-storage-bucketobject-go-zip
    type: container
    name: gcp:storage:BucketObject.go-zip
    external: false
    properties:
      iac.address: gcp:storage:BucketObject.go-zip
      iac.provider_type: gcp_storage_bucketobject
      iac.kind: resource
      filepath: gcp-py-serverless-raw/__main__.py
  - entityRef: infrastructure/gcp-py-serverless-raw/gcp-cloudfunctions-function-go-func
    type: serverless-function
    name: gcp:cloudfunctions:Function.go-func
    external: false
    properties:
      iac.address: gcp:cloudfunctions:Function.go-func
      iac.provider_type: gcp_cloudfunctions_function
      iac.kind: resource
      filepath: gcp-py-serverless-raw/__main__.py
  - entityRef: infrastructure/gcp-py-serverless-raw/gcp-cloudfunctions-functioniammember-go-invoker
    type: serverless-function
    name: gcp:cloudfunctions:FunctionIamMember.go-invoker
    external: false
    properties:
      iac.address: gcp:cloudfunctions:FunctionIamMember.go-invoker
      iac.provider_type: gcp_cloudfunctions_functioniammember
      iac.kind: resource
      filepath: gcp-py-serverless-raw/__main__.py
dependencies:
  - from: infrastructure/gcp-py-serverless-raw/gcp-storage-bucketobject-python-zip
    to: infrastructure/gcp-py-serverless-raw/gcp-storage-bucket-bucket
    type: direct-call
  - from: infrastructure/gcp-py-serverless-raw/gcp-cloudfunctions-function-python-func
    to: infrastructure/gcp-py-serverless-raw/gcp-storage-bucket-bucket
    type: direct-call
  - from: infrastructure/gcp-py-serverless-raw/gcp-cloudfunctions-function-python-func
    to: infrastructure/gcp-py-serverless-raw/gcp-storage-bucketobject-python-zip
    type: direct-call
  - from: infrastructure/gcp-py-serverless-raw/gcp-cloudfunctions-functioniammember-py-invoker
    to: infrastructure/gcp-py-serverless-raw/gcp-cloudfunctions-function-python-func
    type: direct-call
  - from: infrastructure/gcp-py-serverless-raw/gcp-storage-bucketobject-go-zip
    to: infrastructure/gcp-py-serverless-raw/gcp-storage-bucket-bucket
    type: direct-call
  - from: infrastructure/gcp-py-serverless-raw/gcp-cloudfunctions-function-go-func
    to: infrastructure/gcp-py-serverless-raw/gcp-storage-bucket-bucket
    type: direct-call
  - from: infrastructure/gcp-py-serverless-raw/gcp-cloudfunctions-function-go-func
    to: infrastructure/gcp-py-serverless-raw/gcp-storage-bucketobject-go-zip
    type: direct-call
  - from: infrastructure/gcp-py-serverless-raw/gcp-cloudfunctions-functioniammember-go-invoker
    to: infrastructure/gcp-py-serverless-raw/gcp-cloudfunctions-function-go-func
    type: direct-call
