version: https://archlens.dev/schemas/v4/blueprint.schema.json
level: component
metadata:
  entityRef: eshop/ordering-unittests/application
  name: Application Layer Components
  source:
    scannedAtCommit: 9b4f9434f46fdc5c1a6e9e936af2868340cdbc48
    scanRoot: .
    remoteUrl: https://github.com/dotnet/eShop
    defaultBranch: main
nodes:
  - entityRef: eshop/ordering-unittests/application/new-order-command-handler-test
    type: background-worker
    name: NewOrderCommandHandlerTest
    isTest: true
    properties:
      filepath: tests/Ordering.UnitTests/Application/NewOrderCommandHandlerTest.cs
      containerId: ordering-unittests
      technology: C# Domain Service
      classification: default
  - entityRef: eshop/ordering-unittests/application/identified-command-handler-test
    type: background-worker
    name: IdentifiedCommandHandlerTest
    isTest: true
    properties:
      filepath: tests/Ordering.UnitTests/Application/IdentifiedCommandHandlerTest.cs
      containerId: ordering-unittests
      technology: C# Domain Service
      classification: default
  - entityRef: eshop/ordering-unittests/application/orders-web-api-test
    type: rest-api
    name: OrdersWebApiTest
    isTest: true
    properties:
      filepath: tests/Ordering.UnitTests/Application/OrdersWebApiTest.cs
      containerId: ordering-unittests
      technology: ASP.NET Core Controller / Minimal API
      classification: api-marker
  - entityRef: eshop/ordering-unittests/application/set-stock-rejected-order-status-command-test
    type: background-worker
    name: SetStockRejectedOrderStatusCommandTest
    isTest: true
    properties:
      filepath: tests/Ordering.UnitTests/Application/SetStockRejectedOrderStatusCommandTest.cs
      containerId: ordering-unittests
      technology: C# Domain Service
      classification: default
dependencies: []
