import { z } from 'zod';
import type { SystemSchema, NodePosition } from './schema.ts';
import { SYSTEM_SCHEMA_MAJOR_VERSION, systemSchemaPublicUrl } from './schemaVersion.ts';
import { ENTITY_REF_PATTERN } from '../lib/entityRef.ts';
import { getNodePosition } from '../lib/nodePosition.ts';

const nodeTypeSchema = z.enum([
  'person',
  'software-system',

  'web-app',
  'mobile-app',
  'single-page-app',
  'microservice',
  'database',
  'cache-store',
  'event-broker',
  'serverless-app',

  'component',
  'container',
  'code-module',

  'relational-database',
  'grpc-service',
  'serverless-function',
  'rest-api',
  'gateway-api',
  'background-worker',
  'group',
]);

const dependencyTypeSchema = z.enum([
  'direct-call',
  'publish-subscribe',
  'read-write',
  'inter-container',
  'provisions',
]);

/** Shared FQN shape for schema identity and node refs (no file paths). */
const entityRefStringSchema = z
  .string()
  .min(1)
  .regex(
    ENTITY_REF_PATTERN,
    'entityRef must be alphanumeric, dashes or underscores segments separated by slashes'
  );

const forensicClassificationSchema = z.enum(['hotspot', 'knowledge-silo']);

const coupledFileForensicsSchema = z.object({
  path: z.string().min(1),
  score: z.number(),
  sharedCommits: z.number(),
});

const forensicAuthorSchema = z.object({
  email: z.string().min(1),
  commits: z.number().nonnegative(),
});

const nodeForensicsSchema = z.object({
  complexity: z.number().optional(),
  complexityPeak: z.number().optional(),
  cognitiveComplexity: z.number().optional(),
  functionCount: z.number().nonnegative().optional(),
  loc: z.number().optional(),
  sloc: z.number().optional(),
  churn: z.number().optional(),
  lineChurn: z.number().optional(),
  churn30: z.number().optional(),
  churn365: z.number().optional(),
  churnByWeek: z.array(z.number().nonnegative()).optional(),
  hotspotScoreByWeek: z.array(z.number().nonnegative()).optional(),
  authorCount: z.number().optional(),
  topAuthorPercent: z.number().optional(),
  authors: z.array(forensicAuthorSchema).optional(),
  hotspotScore: z.number().optional(),
  classifications: z.array(forensicClassificationSchema).optional(),
  coupledFiles: z.array(coupledFileForensicsSchema).optional(),
  sinceDays: z.number().positive().optional(),
  fileCount: z.number().optional(),
  hotspotCount: z.number().optional(),
  knowledgeSiloCount: z.number().optional(),
});

const nodeSafeguardsPropertySchema = z.object({
  circuitBreaker: z.boolean().optional(),
  bulkhead: z.boolean().optional(),
  retry: z.boolean().optional(),
  localCache: z.boolean().optional(),
});

const nodeResilienceSchema = nodeSafeguardsPropertySchema;

const propertyValueSchema = z.union([z.string(), z.number(), z.boolean()]);

const nodePositionSchema = z.object({
  x: z.number(),
  y: z.number(),
});

const systemNodeSchema = z.object({
  entityRef: entityRefStringSchema,
  type: nodeTypeSchema,
  name: z.string().min(1),
  external: z.boolean().optional(),
  properties: z.record(z.string(), propertyValueSchema).optional(),
  isTest: z.boolean().optional(),
  parentEntityRef: entityRefStringSchema.optional(),
  position: nodePositionSchema.optional(),
  /** @deprecated Accept flat x/y when reading older diagrams; serialize as `position`. */
  x: z.number().optional(),
  y: z.number().optional(),
  forensics: nodeForensicsSchema.optional(),
  resilience: nodeResilienceSchema.optional(),
});

const systemDependencySchema = z.object({
  from: entityRefStringSchema,
  to: entityRefStringSchema,
  type: dependencyTypeSchema,
  description: z.string().optional(),
});

/** Zod contract for blueprint YAML/JSON wire format (v3). Prefer this over hand-written JSON Schema. */
const sourceProvenanceSchema = z.object({
  remoteUrl: z.string().min(1).optional(),
  defaultBranch: z.string().min(1).optional(),
  scannedAtCommit: z.string().min(1).optional(),
  scanRoot: z.string().optional(),
  systemName: z.string().min(1).optional(),
});

const metadataSchema = z.object({
  entityRef: entityRefStringSchema.optional(),
  name: z.string().min(1),
  source: sourceProvenanceSchema.optional(),
});

export const systemSchemaValidator = z.object({
  version: z.string().min(1),
  level: z.enum(['context', 'container', 'component', 'code']),
  metadata: metadataSchema,
  nodes: z.array(systemNodeSchema),
  dependencies: z.array(systemDependencySchema).optional(),
});

/**
 * JSON Schema (Draft 07) derived from {@link systemSchemaValidator} for IDE YAML hints.
 * Documents are a YAML mapping with `version` (schema URL), `level`, `metadata` and `nodes`.
 * Regenerated by `cd app && pnpm generate:schema`.
 * Hosted at {@link systemSchemaPublicUrl} (`/schemas/v{n}/` and `/schemas/latest/`).
 */
export function toSystemSchemaJsonSchema(): Record<string, unknown> {
  const docSchema = z.toJSONSchema(systemSchemaValidator, { target: 'draft-07' }) as Record<
    string,
    unknown
  >;
  delete docSchema.$schema;
  // Drop deprecated flat x/y from the published schema; keep them on the Zod parser only.
  const props = docSchema.properties as Record<string, unknown> | undefined;
  const nodes = props?.nodes as { items?: { properties?: Record<string, unknown> } } | undefined;
  if (nodes?.items?.properties) {
    delete nodes.items.properties.x;
    delete nodes.items.properties.y;
  }
  const versionedId = systemSchemaPublicUrl(`v${SYSTEM_SCHEMA_MAJOR_VERSION}`);
  return {
    ...docSchema,
    $schema: 'http://json-schema.org/draft-07/schema#',
    $id: versionedId,
    title: 'Blueprint System Schema',
    description:
      'Declarative C4 diagram schema used by ArchLens and Canvas. ' +
      'Root is a YAML mapping: version (schema URL), level, metadata (entityRef, name), nodes (with optional position), dependencies. ' +
      'Generated from Zod - do not edit by hand.',
  };
}

function resolveNodePosition(node: {
  position?: NodePosition;
  x?: number;
  y?: number;
}): NodePosition | undefined {
  return getNodePosition(node);
}

function mapValidatedSchema(validated: z.infer<typeof systemSchemaValidator>): SystemSchema {
  return {
    entityRef: validated.metadata.entityRef || '',
    name: validated.metadata.name,
    version: validated.version,
    level: validated.level,
    source: validated.metadata.source,
    nodes: validated.nodes.map(n => {
      const position = resolveNodePosition(n);
      return {
        entityRef: n.entityRef,
        type: n.type,
        name: n.name,
        external: n.external,
        properties: n.properties || {},
        isTest: n.isTest,
        parentEntityRef: n.parentEntityRef,
        ...(position ? { position } : {}),
        forensics: n.forensics,
        resilience: n.resilience,
      };
    }),
    dependencies: validated.dependencies
      ? validated.dependencies.map(d => ({
          from: d.from,
          to: d.to,
          type: d.type,
          description: d.description || '',
        }))
      : [],
  };
}

/** Normalize legacy `metaData` key to `metadata` before Zod validation. */
function normalizeWireDocument(doc: unknown): unknown {
  if (!doc || typeof doc !== 'object' || Array.isArray(doc)) return doc;
  const record = doc as Record<string, unknown>;
  if ('metadata' in record) return record;
  if ('metaData' in record) {
    const { metaData, ...rest } = record;
    return { ...rest, metadata: metaData };
  }
  return record;
}

export function parseWireDocument(doc: unknown): SystemSchema {
  const normalized = normalizeWireDocument(doc);
  if (
    !normalized ||
    typeof normalized !== 'object' ||
    Array.isArray(normalized) ||
    !('metadata' in normalized)
  ) {
    throw new Error(
      'Invalid schema document. Expected an object with version, level and metadata.'
    );
  }
  return mapValidatedSchema(systemSchemaValidator.parse(normalized));
}

export function formatZodError(zodErr: z.ZodError): string {
  return zodErr.issues
    .map(issue => {
      const path = issue.path
        .map((p, idx) => (typeof p === 'number' ? `[${p}]` : (idx > 0 ? '.' : '') + String(p)))
        .join('');
      return `${path || 'root'}: ${issue.message}`;
    })
    .join('; ');
}
