version: https://archlens.dev/schemas/v4/blueprint.schema.json
level: component
metadata:
  entityRef: backstage/packages/backend-defaults/entrypoints/rootconfig
  name: Rootconfig Components
  source:
    remoteUrl: https://github.com/backstage/backstage
    defaultBranch: master
    scannedAtCommit: a052aea0e24911fcac803085ed79f3fe23e0a46e
    scanRoot: .
nodes:
  - entityRef: backstage/packages/backend-defaults/entrypoints/rootconfig/create-config-secret-enumerator
    type: background-worker
    name: CreateConfigSecretEnumerator
    isTest: false
    properties:
      filepath: packages/backend-defaults/src/entrypoints/rootConfig/createConfigSecretEnumerator.ts
      containerId: backend-defaults
      technology: TypeScript Domain Service
      classification: default
  - entityRef: backstage/packages/backend-defaults/entrypoints/rootconfig/create-config-secret-enumerator-test
    type: background-worker
    name: CreateConfigSecretEnumerator
    isTest: true
    properties:
      filepath: packages/backend-defaults/src/entrypoints/rootConfig/createConfigSecretEnumerator.test.ts
      containerId: backend-defaults
      technology: TypeScript Domain Service
      classification: default
  - entityRef: backstage/packages/backend-defaults/entrypoints/rootconfig/root-config-service-factory
    type: background-worker
    name: RootConfigServiceFactory
    isTest: false
    properties:
      filepath: packages/backend-defaults/src/entrypoints/rootConfig/rootConfigServiceFactory.ts
      containerId: backend-defaults
      technology: TypeScript Domain Service
      classification: default
  - entityRef: backstage/packages/backend-defaults/entrypoints/rootconfig/index
    type: background-worker
    name: Index
    isTest: false
    properties:
      filepath: packages/backend-defaults/src/entrypoints/rootConfig/index.ts
      containerId: backend-defaults
      technology: TypeScript Domain Service
      classification: default
  - entityRef: backstage/packages/backend-plugin-api/index
    type: background-worker
    name: Index (External)
    external: true
    properties:
      filepath: packages/backend-plugin-api/src/index.ts
      containerId: backend-plugin-api
      technology: TypeScript Domain Service
      classification: default
    position:
      x: -590
      y: 404
  - entityRef: backstage/packages/config/index
    type: background-worker
    name: Index (External)
    external: true
    properties:
      filepath: packages/config/src/index.ts
      containerId: config
      technology: TypeScript Domain Service
      classification: default
    position:
      x: 790
      y: 404
  - entityRef: backstage/packages/config-loader/index
    type: background-worker
    name: Index (External)
    external: true
    properties:
      filepath: packages/config-loader/src/sources/index.ts
      containerId: config-loader
      technology: TypeScript Domain Service
      classification: default
    position:
      x: 330
      y: 404
  - entityRef: backstage/packages/backend-test-utils/index
    type: background-worker
    name: Index (External)
    external: true
    properties:
      filepath: packages/backend-test-utils/src/util/index.ts
      containerId: backend-test-utils
      technology: TypeScript Domain Service
      classification: default
    position:
      x: -130
      y: 404
dependencies:
  - from: backstage/packages/backend-defaults/entrypoints/rootconfig/create-config-secret-enumerator
    to: backstage/packages/backend-plugin-api/index
    type: direct-call
    description: '@backstage/backend-plugin-api'
  - from: backstage/packages/backend-defaults/entrypoints/rootconfig/create-config-secret-enumerator
    to: backstage/packages/config/index
    type: direct-call
    description: '@backstage/config'
  - from: backstage/packages/backend-defaults/entrypoints/rootconfig/create-config-secret-enumerator
    to: backstage/packages/config-loader/index
    type: direct-call
    description: '@backstage/config-loader'
  - from: backstage/packages/backend-defaults/entrypoints/rootconfig/create-config-secret-enumerator-test
    to: backstage/packages/config-loader/index
    type: direct-call
    description: '@backstage/config-loader'
  - from: backstage/packages/backend-defaults/entrypoints/rootconfig/create-config-secret-enumerator-test
    to: backstage/packages/backend-defaults/entrypoints/rootconfig/create-config-secret-enumerator
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/backend-defaults/entrypoints/rootconfig/create-config-secret-enumerator-test
    to: backstage/packages/backend-test-utils/index
    type: direct-call
    description: '@backstage/backend-test-utils'
  - from: backstage/packages/backend-defaults/entrypoints/rootconfig/root-config-service-factory
    to: backstage/packages/backend-plugin-api/index
    type: direct-call
    description: '@backstage/backend-plugin-api'
  - from: backstage/packages/backend-defaults/entrypoints/rootconfig/root-config-service-factory
    to: backstage/packages/config-loader/index
    type: direct-call
    description: '@backstage/config-loader'
  - from: backstage/packages/backend-defaults/entrypoints/rootconfig/index
    to: backstage/packages/backend-defaults/entrypoints/rootconfig/create-config-secret-enumerator
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/backend-defaults/entrypoints/rootconfig/index
    to: backstage/packages/backend-defaults/entrypoints/rootconfig/root-config-service-factory
    type: direct-call
    description: Calls module / service
