version: https://archlens.dev/schemas/v4/blueprint.schema.json
level: component
metadata:
  entityRef: backstage/packages/repo-tools/commands/package/schema/openapi
  name: Openapi Components
  source:
    remoteUrl: https://github.com/backstage/backstage
    defaultBranch: master
    scannedAtCommit: a052aea0e24911fcac803085ed79f3fe23e0a46e
    scanRoot: .
nodes:
  - entityRef: backstage/packages/repo-tools/commands/package/schema/openapi/generate
    type: background-worker
    name: Generate
    isTest: false
    properties:
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 5
      complexityPeak: 5
      cognitiveComplexity: 10
      churn: 16
      lineChurn: 664
      churn30: 4
      churn365: 16
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2
        - 0
        - 1
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 3
        - 0
        - 0
        - 0
        - 4
        - 2
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 4
        - 0
        - 0
        - 0
        - 0
      authorCount: 5
      topAuthorPercent: 0.5
      authors:
        - email: poldsberg@gmail.com
          commits: 8
        - email: freben@gmail.com
          commits: 3
        - email: 159921952+aramissennyeydd@users.noreply.github.com
          commits: 2
        - email: r_ferreira@outlook.pt
          commits: 2
        - email: rfrferreira98@gmail.com
          commits: 1
      hotspotScore: 0.004435888264708564
      sinceDays: 365
      fileCount: 4
      hotspotCount: 0
      knowledgeSiloCount: 0
  - entityRef: backstage/packages/repo-tools/commands/package/schema/openapi/fuzz
    type: background-worker
    name: Fuzz
    isTest: false
    properties:
      filepath: packages/repo-tools/src/commands/package/schema/openapi/fuzz.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
  - entityRef: backstage/packages/repo-tools/commands/package/schema/openapi/diff
    type: background-worker
    name: Diff
    isTest: false
    properties:
      filepath: packages/repo-tools/src/commands/package/schema/openapi/diff.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
  - entityRef: backstage/packages/repo-tools/openapi/constants
    type: background-worker
    name: Constants (External)
    external: true
    properties:
      filepath: packages/repo-tools/src/lib/openapi/constants.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
    position:
      x: 560
      y: 404
  - entityRef: backstage/packages/repo-tools/openapi/helpers
    type: background-worker
    name: Helpers (External)
    external: true
    properties:
      filepath: packages/repo-tools/src/lib/openapi/helpers.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
    position:
      x: 1020
      y: 404
  - entityRef: backstage/packages/cli-common/index
    type: background-worker
    name: Index (External)
    external: true
    properties:
      filepath: packages/cli-common/src/index.ts
      containerId: cli-common
      technology: TypeScript Domain Service
      classification: default
    position:
      x: -820
      y: 404
  - entityRef: backstage/packages/config-loader/index
    type: background-worker
    name: Index (External)
    external: true
    properties:
      filepath: packages/config-loader/src/sources/index.ts
      containerId: config-loader
      technology: TypeScript Domain Service
      classification: default
    position:
      x: -360
      y: 404
  - entityRef: backstage/packages/repo-tools/commands/util
    type: background-worker
    name: Util (External)
    external: true
    properties:
      filepath: packages/repo-tools/src/commands/util.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
    position:
      x: 100
      y: 404
dependencies:
  - from: backstage/packages/repo-tools/commands/package/schema/openapi/fuzz
    to: backstage/packages/cli-common/index
    type: direct-call
    description: '@backstage/cli-common'
  - from: backstage/packages/repo-tools/commands/package/schema/openapi/fuzz
    to: backstage/packages/repo-tools/exec/exec
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/repo-tools/commands/package/schema/openapi/fuzz
    to: backstage/packages/repo-tools/openapi/helpers
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/repo-tools/commands/package/schema/openapi/fuzz
    to: backstage/packages/config-loader/index
    type: direct-call
    description: '@backstage/config-loader'
  - from: backstage/packages/repo-tools/commands/package/schema/openapi/diff
    to: backstage/packages/repo-tools/exec/exec
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/repo-tools/commands/package/schema/openapi/diff
    to: backstage/packages/repo-tools/openapi/constants
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/repo-tools/commands/package/schema/openapi/diff
    to: backstage/packages/repo-tools/openapi/helpers
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/repo-tools/commands/package/schema/openapi/diff
    to: backstage/packages/repo-tools/commands/util
    type: direct-call
    description: Calls module / service
  - from: backstage/packages/repo-tools/commands/package/schema/openapi/diff
    to: backstage/packages/cli-common/index
    type: direct-call
    description: '@backstage/cli-common'
