#!/usr/bin/env bun
/**
 * Write src/cli/buildVersion.generated.ts before compiling the standalone binary.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outFile = path.join(packageRoot, 'src/cli/buildVersion.generated.ts');

const version = process.env.ARCHLENS_VERSION?.trim() || 'dev';
const escaped = version.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

const contents = `// Generated by scripts/emitBuildVersion.ts - do not edit.
export const ARCHLENS_BUILD_VERSION = '${escaped}';
`;

fs.writeFileSync(outFile, contents, 'utf8');
console.log(`Wrote ${outFile} (${version})`);
