version: https://archlens.dev/schemas/v4/blueprint.schema.json
level: component
metadata:
  entityRef: blueprint/app/designer/infrastructure/db
  name: Db Components
  source:
    remoteUrl: https://github.com/mzworthington/blueprint
    defaultBranch: main
    scannedAtCommit: ffbf467109f8056fcf1b6dd3a78fb6dbc0074362
    scanRoot: .
nodes:
  - entityRef: blueprint/app/designer/infrastructure/db/dexie-working-copy-adapter
    type: relational-database
    name: DexieWorkingCopyAdapter
    isTest: false
    properties:
      filepath: app/packages/designer/src/infrastructure/db/dexieWorkingCopyAdapter.ts
      containerId: designer
      technology: Prisma / SQL Database Client
      classification: database-marker
  - entityRef: blueprint/app/designer/infrastructure/db/db-test
    type: relational-database
    name: Db
    isTest: true
    properties:
      filepath: app/packages/designer/src/infrastructure/db/db.test.ts
      containerId: designer
      technology: Prisma / SQL Database Client
      classification: database-marker
  - entityRef: blueprint/app/designer/core
    type: background-worker
    name: Core (External)
    external: true
    properties:
      containerId: designer
      technology: TypeScript Domain Service
      classification: default
    position:
      x: 330
      y: 404
  - entityRef: blueprint/app/core/index
    type: background-worker
    name: Index (External)
    external: true
    properties:
      filepath: app/packages/core/src/index.ts
      containerId: core
      technology: TypeScript Domain Service
      classification: default
    position:
      x: -130
      y: 404
dependencies:
  - from: blueprint/app/designer/infrastructure/db/dexie-working-copy-adapter
    to: blueprint/app/core/index
    type: direct-call
    description: '@archlens/core'
  - from: blueprint/app/designer/infrastructure/db/dexie-working-copy-adapter
    to: blueprint/app/designer/core
    type: direct-call
    description: Calls module / service
  - from: blueprint/app/designer/infrastructure/db/dexie-working-copy-adapter
    to: blueprint/app/designer/infrastructure/db
    type: read-write
    description: Queries datastore records
  - from: blueprint/app/designer/infrastructure/db/db-test
    to: blueprint/app/designer/infrastructure/db
    type: read-write
    description: Queries datastore records
  - from: blueprint/app/designer/infrastructure/db/db-test
    to: blueprint/app/core/index
    type: direct-call
    description: '@archlens/core'
