version: https://archlens.dev/schemas/v4/blueprint.schema.json
level: component
metadata:
  entityRef: backstage/packages/repo-tools/openapi
  name: Openapi Components
  source:
    remoteUrl: https://github.com/backstage/backstage
    defaultBranch: master
    scannedAtCommit: a052aea0e24911fcac803085ed79f3fe23e0a46e
    scanRoot: .
nodes:
  - entityRef: backstage/packages/repo-tools/openapi/helpers
    type: background-worker
    name: Helpers
    isTest: false
    properties:
      filepath: packages/repo-tools/src/lib/openapi/helpers.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
  - entityRef: backstage/packages/repo-tools/openapi/dedupe-imports
    type: background-worker
    name: Dedupe imports
    isTest: false
    properties:
      filepath: packages/repo-tools/src/lib/openapi/dedupe-imports.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
  - entityRef: backstage/packages/repo-tools/openapi/constants
    type: background-worker
    name: Constants
    isTest: false
    properties:
      filepath: packages/repo-tools/src/lib/openapi/constants.ts
      containerId: repo-tools
      technology: TypeScript Domain Service
      classification: default
  - entityRef: backstage/packages/cli-common/index
    type: background-worker
    name: Index (External)
    external: true
    properties:
      filepath: packages/cli-common/src/index.ts
      containerId: cli-common
      technology: TypeScript Domain Service
      classification: default
    position:
      x: 100
      y: 404
dependencies:
  - from: backstage/packages/repo-tools/openapi/helpers
    to: backstage/packages/cli-common/index
    type: direct-call
    description: '@backstage/cli-common'
  - from: backstage/packages/repo-tools/openapi/helpers
    to: backstage/packages/repo-tools/openapi/constants
    type: direct-call
    description: Calls module / service
