import * as yaml from 'js-yaml';
import { z } from 'zod';
import { ENTITY_REF_PATTERN } from '../lib/entityRef';
import { CHAOS_SCHEMA_MAJOR_VERSION, chaosSchemaPublicUrl } from '../models/chaosVersion';
import type { EntityRef, SystemSchema } from '../models/schema';
import type { ChaosSpec, FaultType, NodeFaultConfig, NodeSafeguards } from './faultSpec';
import type { MonteCarloConfig } from './wasmClient';

const entityRefStringSchema = z
  .string()
  .min(1)
  .regex(
    ENTITY_REF_PATTERN,
    'entityRef must be alphanumeric, dashes, or underscores segments separated by slashes'
  );

const faultTypeSchema = z.enum(['latency', 'error-rate', 'packet-loss', 'region-outage']);

const nodeSafeguardsSchema = z.object({
  circuitBreaker: z.boolean().optional(),
  bulkhead: z.boolean().optional(),
  retry: z.boolean().optional(),
  localCache: z.boolean().optional(),
});

const nodeFaultConfigSchema = z.object({
  nodeId: entityRefStringSchema,
  faultType: faultTypeSchema,
  severity: z.number().min(0).max(1).optional(),
  safeguards: nodeSafeguardsSchema.optional(),
});

const monteCarloConfigSchema = z.object({
  iterations: z.number().int().positive(),
  seed: z.number().int().positive().optional(),
  severityJitter: z.number().min(0).max(1).optional(),
});

const chaosSpecMetadataSchema = z.object({
  name: z.string().min(1),
  description: z.string().min(1).optional(),
  diagramRef: entityRefStringSchema,
});

export const chaosSpecDocumentValidator = z.object({
  version: z.string().min(1),
  metadata: chaosSpecMetadataSchema,
  faults: z.array(nodeFaultConfigSchema).min(1),
  safeguards: z.record(entityRefStringSchema, nodeSafeguardsSchema).optional(),
  monteCarlo: monteCarloConfigSchema.optional(),
});

export type ChaosSpecMetadata = z.infer<typeof chaosSpecMetadataSchema>;
export type ChaosSpecDocument = {
  version: string;
  metadata: ChaosSpecMetadata;
  faults: NodeFaultConfig[];
  safeguards?: Partial<Record<EntityRef, NodeSafeguards>>;
  monteCarlo?: MonteCarloConfig;
};

export interface ChaosSpecRuntimeBundle {
  spec: ChaosSpec;
  monteCarlo?: MonteCarloConfig;
}

/**
 * JSON Schema (Draft 07) derived from {@link chaosSpecDocumentValidator} for IDE YAML hints.
 * Regenerated by `cd app && pnpm generate:schema`.
 */
export function toChaosSpecJsonSchema(): Record<string, unknown> {
  const docSchema = z.toJSONSchema(chaosSpecDocumentValidator, { target: 'draft-07' }) as Record<
    string,
    unknown
  >;
  delete docSchema.$schema;
  const versionedId = chaosSchemaPublicUrl(`v${CHAOS_SCHEMA_MAJOR_VERSION}`);
  return {
    ...docSchema,
    $schema: 'http://json-schema.org/draft-07/schema#',
    $id: versionedId,
    title: 'ChaosSpec',
    description:
      'Declarative ChaosLens scenario: faults, safeguard overrides, and Monte Carlo config. ' +
      'References a BlueprintSpec diagram by metadata.diagramRef - does not duplicate topology. ' +
      'Generated from Zod - do not edit by hand.',
  };
}

export function parseChaosSpecFromYaml(yamlContent: string): ChaosSpecDocument {
  const raw = yaml.load(yamlContent);
  const parsed = chaosSpecDocumentValidator.safeParse(raw);
  if (!parsed.success) {
    const message = parsed.error.issues.map(issue => issue.message).join('; ');
    throw new Error(`Invalid ChaosSpec YAML: ${message}`);
  }

  return {
    version: parsed.data.version,
    metadata: parsed.data.metadata,
    faults: parsed.data.faults.map(fault => ({
      nodeId: fault.nodeId,
      faultType: fault.faultType as FaultType,
      ...(fault.severity != null ? { severity: fault.severity } : {}),
      ...(fault.safeguards ? { safeguards: fault.safeguards } : {}),
    })),
    ...(parsed.data.safeguards ? { safeguards: parsed.data.safeguards } : {}),
    ...(parsed.data.monteCarlo ? { monteCarlo: parsed.data.monteCarlo } : {}),
  };
}

/** Strip document metadata for the simulation engine. */
export function chaosSpecDocumentToRuntime(document: ChaosSpecDocument): ChaosSpecRuntimeBundle {
  return {
    spec: {
      faults: document.faults,
      ...(document.safeguards ? { safeguards: document.safeguards } : {}),
    },
    ...(document.monteCarlo ? { monteCarlo: document.monteCarlo } : {}),
  };
}

export function chaosSpecTargetsDiagram(
  document: ChaosSpecDocument,
  activeDiagramRef: string
): boolean {
  return document.metadata.diagramRef === activeDiagramRef;
}

/** Returns an error message when the spec cannot run against the active diagram. */
export function validateChaosSpecForDiagram(
  document: ChaosSpecDocument,
  schema: Pick<SystemSchema, 'nodes'>,
  activeDiagramRef: string
): string | null {
  if (!chaosSpecTargetsDiagram(document, activeDiagramRef)) {
    return `ChaosSpec targets ${document.metadata.diagramRef} but the active diagram is ${activeDiagramRef}.`;
  }

  const nodeRefs = new Set(schema.nodes.map(node => node.entityRef));
  for (const fault of document.faults) {
    if (!nodeRefs.has(fault.nodeId)) {
      return `Fault target ${fault.nodeId} is not on the active diagram.`;
    }
  }

  return null;
}
