import * as yaml from 'js-yaml';
import { z } from 'zod';
import { ENTITY_REF_PATTERN } from '../lib/entityRef';
import {
  CHAOS_SCHEMA_MAJOR_VERSION,
  chaosSchemaPublicUrl,
  chaosYamlLanguageServerDirective,
} from '../models/chaosVersion';
import type { EntityRef, SystemSchema } from '../models/schema';
import type { ChaosSpec, FaultType, NodeFaultConfig, NodeSafeguards } from './faultSpec';
import type { MonteCarloConfig } from './monteCarlo';

const entityRefStringSchema = z
  .string()
  .min(1)
  .regex(
    ENTITY_REF_PATTERN,
    'entityRef must be alphanumeric, dashes, or underscores segments separated by slashes'
  );

const faultTypeSchema = z.enum(['latency', 'error-rate', 'packet-loss', 'region-outage']);

const nodeSafeguardsSchema = z.object({
  circuitBreaker: z.boolean().optional(),
  bulkhead: z.boolean().optional(),
  retry: z.boolean().optional(),
  localCache: z.boolean().optional(),
});

const nodeFaultConfigSchema = z.object({
  nodeId: entityRefStringSchema,
  faultType: faultTypeSchema,
  severity: z.number().min(0).max(1).optional(),
  safeguards: nodeSafeguardsSchema.optional(),
});

const monteCarloConfigSchema = z.object({
  iterations: z.number().int().positive(),
  seed: z.number().int().positive().optional(),
  severityJitter: z.number().min(0).max(1).optional(),
});

const chaosSpecMetadataSchema = z.object({
  name: z.string().min(1),
  description: z.string().min(1).optional(),
  diagramRef: entityRefStringSchema,
});

export const chaosSpecDocumentValidator = z.object({
  version: z.string().min(1),
  metadata: chaosSpecMetadataSchema,
  faults: z.array(nodeFaultConfigSchema).min(1),
  safeguards: z.record(entityRefStringSchema, nodeSafeguardsSchema).optional(),
  monteCarlo: monteCarloConfigSchema.optional(),
});

export type ChaosSpecMetadata = z.infer<typeof chaosSpecMetadataSchema>;
export type ChaosSpecDocument = {
  version: string;
  metadata: ChaosSpecMetadata;
  faults: NodeFaultConfig[];
  safeguards?: Partial<Record<EntityRef, NodeSafeguards>>;
  monteCarlo?: MonteCarloConfig;
};

export interface ChaosSpecRuntimeBundle {
  spec: ChaosSpec;
  monteCarlo?: MonteCarloConfig;
}

/**
 * JSON Schema (Draft 07) derived from {@link chaosSpecDocumentValidator} for IDE YAML hints.
 * Regenerated by `cd app && pnpm generate:schema`.
 */
export function toChaosSpecJsonSchema(): Record<string, unknown> {
  const docSchema = z.toJSONSchema(chaosSpecDocumentValidator, { target: 'draft-07' }) as Record<
    string,
    unknown
  >;
  delete docSchema.$schema;
  const versionedId = chaosSchemaPublicUrl(`v${CHAOS_SCHEMA_MAJOR_VERSION}`);
  return {
    ...docSchema,
    $schema: 'http://json-schema.org/draft-07/schema#',
    $id: versionedId,
    title: 'ChaosSpec',
    description:
      'Declarative ChaosLens scenario: faults, safeguard overrides, and Monte Carlo config. ' +
      'References a BlueprintSpec diagram by metadata.diagramRef - does not duplicate topology. ' +
      'Generated from Zod - do not edit by hand.',
  };
}

export function parseChaosSpecFromYaml(yamlContent: string): ChaosSpecDocument {
  const raw = yaml.load(yamlContent);
  const parsed = chaosSpecDocumentValidator.safeParse(raw);
  if (!parsed.success) {
    const message = parsed.error.issues.map(issue => issue.message).join('; ');
    throw new Error(`Invalid ChaosSpec YAML: ${message}`);
  }

  return {
    version: parsed.data.version,
    metadata: parsed.data.metadata,
    faults: parsed.data.faults.map(fault => ({
      nodeId: fault.nodeId,
      faultType: fault.faultType as FaultType,
      ...(fault.severity != null ? { severity: fault.severity } : {}),
      ...(fault.safeguards ? { safeguards: fault.safeguards } : {}),
    })),
    ...(parsed.data.safeguards ? { safeguards: parsed.data.safeguards } : {}),
    ...(parsed.data.monteCarlo ? { monteCarlo: parsed.data.monteCarlo } : {}),
  };
}

/** Strip document metadata for the simulation engine. */
export function chaosSpecDocumentToRuntime(document: ChaosSpecDocument): ChaosSpecRuntimeBundle {
  return {
    spec: {
      faults: document.faults,
      ...(document.safeguards ? { safeguards: document.safeguards } : {}),
    },
    ...(document.monteCarlo ? { monteCarlo: document.monteCarlo } : {}),
  };
}

export function chaosSpecTargetsDiagram(
  document: ChaosSpecDocument,
  activeDiagramRef: string
): boolean {
  return document.metadata.diagramRef === activeDiagramRef;
}

/** Returns an error message when the spec cannot run against the active diagram. */
export function validateChaosSpecForDiagram(
  document: ChaosSpecDocument,
  schema: Pick<SystemSchema, 'nodes' | 'dependencies'>,
  activeDiagramRef: string
): string | null {
  if (!chaosSpecTargetsDiagram(document, activeDiagramRef)) {
    return `ChaosSpec targets ${document.metadata.diagramRef} but the active diagram is ${activeDiagramRef}.`;
  }

  const nodeRefs = new Set(schema.nodes.map(node => node.entityRef));
  const dependencyRefs = new Set((schema.dependencies ?? []).flatMap(dep => [dep.from, dep.to]));
  for (const fault of document.faults) {
    if (!nodeRefs.has(fault.nodeId) && !dependencyRefs.has(fault.nodeId)) {
      return `Fault target ${fault.nodeId} is not on the active diagram.`;
    }
  }

  return null;
}

function pruneSafeguards(
  safeguards: Partial<Record<EntityRef, NodeSafeguards>>
): Partial<Record<EntityRef, NodeSafeguards>> | undefined {
  const out: Partial<Record<EntityRef, NodeSafeguards>> = {};
  for (const [nodeId, safeguardsForNode] of Object.entries(safeguards)) {
    if (!safeguardsForNode) continue;
    const cleaned: NodeSafeguards = {};
    if (safeguardsForNode.circuitBreaker) cleaned.circuitBreaker = true;
    if (safeguardsForNode.bulkhead) cleaned.bulkhead = true;
    if (safeguardsForNode.retry) cleaned.retry = true;
    if (safeguardsForNode.localCache) cleaned.localCache = true;
    if (Object.keys(cleaned).length > 0) {
      out[nodeId as EntityRef] = cleaned;
    }
  }
  return Object.keys(out).length > 0 ? out : undefined;
}

function faultToWireRecord(fault: NodeFaultConfig): Record<string, unknown> {
  const record: Record<string, unknown> = {
    nodeId: fault.nodeId,
    faultType: fault.faultType,
  };
  if (fault.severity != null && fault.severity !== 1) {
    record.severity = fault.severity;
  }
  if (fault.safeguards && Object.keys(fault.safeguards).length > 0) {
    record.safeguards = fault.safeguards;
  }
  return record;
}

/** Build a ChaosSpec document from the active scenario (no topology duplication). */
export function buildChaosSpecDocument(input: {
  diagramRef: string;
  name: string;
  description?: string;
  faults: NodeFaultConfig[];
  safeguards?: Partial<Record<EntityRef, NodeSafeguards>>;
  monteCarlo?: MonteCarloConfig;
}): ChaosSpecDocument {
  if (input.faults.length === 0) {
    throw new Error('Cannot export a ChaosSpec with no faults.');
  }

  const safeguards = input.safeguards ? pruneSafeguards(input.safeguards) : undefined;

  return {
    version: chaosSchemaPublicUrl(`v${CHAOS_SCHEMA_MAJOR_VERSION}`),
    metadata: {
      name: input.name,
      diagramRef: input.diagramRef,
      ...(input.description ? { description: input.description } : {}),
    },
    faults: input.faults.map(fault => ({
      nodeId: fault.nodeId,
      faultType: fault.faultType,
      ...(fault.severity != null && fault.severity !== 1 ? { severity: fault.severity } : {}),
      ...(fault.safeguards ? { safeguards: fault.safeguards } : {}),
    })),
    ...(safeguards ? { safeguards } : {}),
    ...(input.monteCarlo ? { monteCarlo: input.monteCarlo } : {}),
  };
}

/** Serialize a ChaosSpec document to YAML for version control or export. */
export function serializeChaosSpecToYaml(
  document: ChaosSpecDocument,
  options?: { schemaUrl?: string }
): string {
  const wire: Record<string, unknown> = {
    version: document.version,
    metadata: {
      name: document.metadata.name,
      diagramRef: document.metadata.diagramRef,
      ...(document.metadata.description ? { description: document.metadata.description } : {}),
    },
    faults: document.faults.map(faultToWireRecord),
  };

  if (document.safeguards && Object.keys(document.safeguards).length > 0) {
    wire.safeguards = document.safeguards;
  }
  if (document.monteCarlo) {
    wire.monteCarlo = document.monteCarlo;
  }

  const body = yaml.dump(wire, { noRefs: true, lineWidth: 120 });
  return `${chaosYamlLanguageServerDirective(options?.schemaUrl)}\n${body}`;
}
